package services

import (
	"context"
	"fmt"
	"math/rand"
	"strings"
	"time"

	"github.com/joaopedro/hivemind/internal/models"
)

// MockInferenceService provides realistic mock inference responses.
type MockInferenceService struct {
	roomSvc RoomService
}

// NewMockInferenceService creates a mock inference service.
func NewMockInferenceService(roomSvc RoomService) *MockInferenceService {
	return &MockInferenceService{roomSvc: roomSvc}
}

func (s *MockInferenceService) ChatCompletion(_ context.Context, req models.ChatRequest) (*models.ChatResponse, error) {
	room := s.roomSvc.CurrentRoom()
	if room == nil {
		return nil, models.ErrNotInRoom
	}

	lastMsg := ""
	if len(req.Messages) > 0 {
		lastMsg = req.Messages[len(req.Messages)-1].Content
	}

	response := generateMockResponse(lastMsg)
	promptTokens := countTokens(lastMsg)
	completionTokens := countTokens(response)

	resp := models.NewChatResponse(
		fmt.Sprintf("hm-%s", generateID(6)),
		req.Model,
		response,
	)
	resp.Usage = models.UsageStats{
		PromptTokens:     promptTokens,
		CompletionTokens: completionTokens,
		TotalTokens:      promptTokens + completionTokens,
	}

	return &resp, nil
}

func (s *MockInferenceService) ChatCompletionStream(_ context.Context, req models.ChatRequest, ch chan<- models.ChatChunk) error {
	defer close(ch)

	room := s.roomSvc.CurrentRoom()
	if room == nil {
		return models.ErrNotInRoom
	}

	lastMsg := ""
	if len(req.Messages) > 0 {
		lastMsg = req.Messages[len(req.Messages)-1].Content
	}

	response := generateMockResponse(lastMsg)
	words := strings.Fields(response)
	requestID := fmt.Sprintf("hm-%s", generateID(6))

	// Send role chunk
	ch <- models.ChatChunk{
		ID:      requestID,
		Object:  "chat.completion.chunk",
		Created: time.Now().Unix(),
		Model:   req.Model,
		Choices: []models.ChatChunkChoice{
			{
				Index: 0,
				Delta: models.ChatChunkDelta{Role: "assistant"},
			},
		},
	}

	// Stream words with realistic delay
	for i, word := range words {
		delay := time.Duration(30+rand.Intn(70)) * time.Millisecond
		time.Sleep(delay)

		content := word
		if i < len(words)-1 {
			content += " "
		}

		ch <- models.ChatChunk{
			ID:      requestID,
			Object:  "chat.completion.chunk",
			Created: time.Now().Unix(),
			Model:   req.Model,
			Choices: []models.ChatChunkChoice{
				{
					Index: 0,
					Delta: models.ChatChunkDelta{Content: content},
				},
			},
		}
	}

	// Send done chunk
	finishReason := "stop"
	ch <- models.ChatChunk{
		ID:      requestID,
		Object:  "chat.completion.chunk",
		Created: time.Now().Unix(),
		Model:   req.Model,
		Choices: []models.ChatChunkChoice{
			{
				Index:        0,
				Delta:        models.ChatChunkDelta{},
				FinishReason: &finishReason,
			},
		},
	}

	return nil
}

func (s *MockInferenceService) ImageGeneration(_ context.Context, req models.ImageRequest) (*models.ImageResponse, error) {
	room := s.roomSvc.CurrentRoom()
	if room == nil {
		return nil, models.ErrNotInRoom
	}

	// Simulate generation delay
	time.Sleep(2 * time.Second)

	return &models.ImageResponse{
		Created: time.Now().Unix(),
		Data: []models.ImageData{
			{B64JSON: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="},
		},
	}, nil
}

func (s *MockInferenceService) ListModels(_ context.Context) (*models.ModelList, error) {
	room := s.roomSvc.CurrentRoom()
	if room == nil {
		return &models.ModelList{
			Object: "list",
			Data:   []models.ModelInfo{},
		}, nil
	}

	return &models.ModelList{
		Object: "list",
		Data: []models.ModelInfo{
			{
				ID:      room.ModelID,
				Object:  "model",
				OwnedBy: "hivemind-room",
			},
		},
	}, nil
}

// generateMockResponse creates a realistic-looking AI response.
func generateMockResponse(input string) string {
	responses := []string{
		"This is a distributed inference response generated by HiveMind across multiple nodes. The model layers were split between peers in the room, with each node processing its assigned layers and passing activation tensors to the next node in the pipeline.",
		"HiveMind is processing your request using tensor parallelism. The input was tokenized locally, sent through layers 0-19 on the host, then the intermediate tensors were transferred to peer-1 for layers 20-39, and finally to peer-2 for layers 40-59. The output was decoded back into text.",
		"Great question! In a distributed setting like HiveMind, the model is partitioned across participating nodes based on their available VRAM. Each node loads and processes only its assigned layers, making it possible to run models that would otherwise require significantly more memory than any single machine has.",
		"The cooperative inference approach means that everyone in the room contributes their computing resources. No single machine needs enough VRAM for the entire model. By connecting via a WireGuard mesh network, the nodes communicate securely and efficiently to perform distributed tensor operations.",
	}

	return responses[rand.Intn(len(responses))]
}

// countTokens provides a rough token estimate (~4 chars per token).
func countTokens(text string) int {
	if len(text) == 0 {
		return 0
	}
	return len(text)/4 + 1
}
